### PR TITLE
Update instruments to use avdmanager

### PR DESCRIPTION
**Pull request by joshrlesch**

### CODE REVIEW

**Comment by dustinrwh** [comment]
Is there a plan to merge this into master at some point? 

This should fix my issue because `--target` is throwing it off. What happens is it calls `android create avd...`, realizes it is deprecated and runs `avdmanager create avd ...` with the same `--target` parameter which is no longer supported.

**Comment by joshrlesch** [comment]
If I get some time this week, I'll try to get it merged. Can't remember if I test if it works or not.

**Comment by dustinrwh** [comment]
Sounds good. I'm actually currently testing this branch so I'll let you
know how it goes :)

2017-11-08 11:02 GMT-08:00 Josh Lesch <notifications@github.com>:

**Comment by dustinrwh** [comment]
Had some time to get this working and I've submitted a pull request #11. There were a couple bugs, but it all seems to be working now 👍

**Pull request merged**
